apiVersion: skaffold/v2alpha3 
kind: Config 
deploy: 
    kubectl: 
        manifests: 
            - ./infra/k8s/* 
build: 
    # local: 
    #     push: false 
    ## Telling skaffold to use google build to build image 
    ## instead of the local machine      
    googleCloudBuild: 
      projectId: ticketing-dev-281911
    artifacts: 
        ## specify the name which google build will give 
        ## to the image built ## us.gcr.io/ticketing-dev-281911/<projectId>/<name_of_directory>
        - image: gcr.io/ticketing-dev-281911/auth
          context: auth ## folder where the dockerfile is 
          docker: 
            dockerfile: Dockerfile ## name of dockerfile 
          sync: 
            manual: 
                - src: 'src/**/*.ts'
                  dest: . 
        - image: gcr.io/ticketing-dev-281911/client 
          context: client 
          docker: 
            dockerfile: Dockerfile 
          sync: 
            manual: 
              - src: '**/*.js'
                dest: . 
        - image: gcr.io/ticketing-dev-281911/tickets 
          context: tickets 
          docker: 
            dockerfile: Dockerfile
          sync: 
            manual:
              - src: '**/*.ts'
                dest: .