apiVersion: apps/v1 
kind: Deployment 
metadata: 
    name: auth-depl 
spec: 
    replicas: 1 
    selector: 
        matchLabels:
            app: auth
    template: 
        metadata: 
            labels: 
                app: auth 
        spec: 
            containers: 
                - name: auth 
                  image: gcr.io/ticketing-dev-281911/auth
                  env: 
                    - name: JWT_KEY
                      valueFrom: 
                        secretKeyRef: 
                            ## name of the secret we created imperatively
                            name: jwt-secret 
                            key: JWT_KEY
--- 
apiVersion: v1 
kind: Service 
metadata: 
    name: auth-srv 
spec: 
    type: ClusterIP
    selector: 
        app: auth 
    ports: 
        - name: auth 
          protocol: TCP 
          port: 3000 
          targetPort: 3000 
    